//! Rendering of `registry.rs` and `detail.json.gz`. Both are deterministic: no timestamps,
//! sorted keys, a fixed gzip header.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::io::Write as _;

use anyhow::{Context, Result};
use flate2::{Compression, GzBuilder};
use serde_json::Value;

use super::{Op, ParamDef};
use crate::specs::SpecVersions;

pub const HEADER: &str = "// @generated by `cargo xtask codegen` from specs/*.yaml — DO NOT EDIT";

/// A Rust string literal for `s` (via `Debug`, which escapes quotes, backslashes and controls).
fn lit(s: &str) -> String {
    format!("{s:?}")
}

fn opt_lit(s: Option<&str>) -> String {
    s.map_or_else(|| "None".to_owned(), |v| format!("Some({})", lit(v)))
}

fn param(p: &ParamDef) -> String {
    format!(
        "Param {{ name: {}, location: {}, ty: {}, required: {}, deep_object: {} }}",
        lit(&p.name),
        p.location.rust(),
        p.ty.rust(),
        p.required,
        p.deep_object
    )
}

/// The full text of `crates/zdk-core/src/api/generated/registry.rs`.
pub fn registry(ops: &[Op], versions: &SpecVersions) -> String {
    let mut out = String::with_capacity(1 << 20);
    let _ = writeln!(out, "{HEADER}");
    let _ = writeln!(
        out,
        "// Regenerate with `cargo xtask codegen`; CI runs `cargo xtask codegen --check`."
    );
    let _ = writeln!(out, "#![allow(clippy::all, clippy::pedantic)]");
    let _ = writeln!(out);
    let _ = writeln!(out, "use crate::api::*;");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "/// Every documented operation, sorted by `(spec, path, method)`. {} entries.",
        ops.len()
    );
    let _ = writeln!(out, "#[rustfmt::skip]");
    let _ = writeln!(out, "pub static OPERATIONS: &[Operation] = &[");
    for op in ops {
        let _ = write!(
            out,
            "    Operation {{ spec: {}, id: {}, method: {}, path: {}, tag: {}, summary: {},",
            op.spec.rust(),
            lit(&op.id),
            op.method.rust(),
            lit(&op.path),
            lit(&op.tag),
            lit(&op.summary)
        );
        if op.params.is_empty() {
            let _ = writeln!(out, " params: &[],");
        } else {
            let _ = writeln!(out);
            let _ = writeln!(out, "        params: &[");
            for p in &op.params {
                let _ = writeln!(out, "            {},", param(p));
            }
            let _ = writeln!(out, "        ],");
        }
        let _ = writeln!(
            out,
            "        body: {}, items_key: {}, pagination: {}, scope: {}, deprecated: {} }},",
            op.body.rust(),
            opt_lit(op.items_key.as_deref()),
            op.pagination.rust(),
            opt_lit(op.scope.as_deref()),
            op.deprecated
        );
    }
    let _ = writeln!(out, "];");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "/// The committed spec snapshots, mirrored from `specs/SPEC_VERSIONS.toml`."
    );
    let _ = writeln!(out, "#[rustfmt::skip]");
    let _ = writeln!(out, "pub static SPEC_VERSIONS: &[SpecVersion] = &[");
    for (spec, e) in &versions.entries {
        let _ = writeln!(
            out,
            "    SpecVersion {{ spec: {}, url: {}, openapi: {}, info_version: {}, sha256: {}, fetched_at: {}, paths: {}, operations: {} }},",
            spec.rust(),
            lit(&e.url),
            lit(&e.openapi),
            lit(&e.info_version),
            lit(&e.sha256),
            lit(&e.fetched_at),
            e.paths,
            e.operations
        );
    }
    let _ = writeln!(out, "];");
    out
}

/// `detail.json.gz`: a gzip (mtime 0, OS byte 255) of the JSON object `{ "<spec>.<id>": … }`
/// with keys in sorted order.
pub fn detail(entries: &BTreeMap<String, Value>) -> Result<Vec<u8>> {
    let mut map = serde_json::Map::with_capacity(entries.len());
    for (k, v) in entries {
        map.insert(k.clone(), v.clone());
    }
    let json = serde_json::to_vec(&Value::Object(map)).context("serialising detail payload")?;
    let mut gz = GzBuilder::new()
        .mtime(0)
        .operating_system(255)
        .write(Vec::new(), Compression::best());
    gz.write_all(&json).context("compressing detail payload")?;
    gz.finish().context("finishing gzip stream")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn literals_are_escaped() {
        assert_eq!(lit("a \"b\" \\ c\nd"), "\"a \\\"b\\\" \\\\ c\\nd\"");
        assert_eq!(opt_lit(None), "None");
        assert_eq!(opt_lit(Some("x")), "Some(\"x\")");
    }

    #[test]
    fn gzip_header_is_fixed() {
        let a = detail(&BTreeMap::new()).expect("gz");
        let b = detail(&BTreeMap::new()).expect("gz");
        assert_eq!(a, b);
        assert_eq!(&a[..10], &[0x1f, 0x8b, 8, 0, 0, 0, 0, 0, 2, 255]);
    }
}
