//! The clap command tree: global flags (PRD §7.1) and top-level commands.

use std::path::PathBuf;

use clap::{ArgAction, Args, Parser, Subcommand, ValueEnum};
use zdk_core::config::{GlobalArgs, RateLimitStrategy};
use zdk_core::output::OutputFormat;
use zdk_core::store::StoreSelector;

const LONG_ABOUT: &str = "\
Zendesk CLI for AI agents and support operations.

stdout carries data only (plain JSON when piped, tables on a terminal); every
diagnostic goes to stderr; exit codes are stable (see `zdk --help-json`).

  0 ok   1 error   2 usage   3 auth   4 forbidden   5 not found   6 validation
  7 rate limited   9 server   10 config   11 network   12 pagination limit   130 interrupted";

#[derive(Debug, Parser)]
#[command(
    name = "zdk",
    bin_name = "zdk", // usage lines must not become `zdk.exe` on Windows (help snapshots)
    version,
    about = "Zendesk CLI for AI agents and support operations",
    long_about = LONG_ABOUT,
    propagate_version = true,
    disable_help_subcommand = true,
    after_help = "Run `zdk config init` to get started, then `zdk auth login`."
)]
pub struct Cli {
    #[command(flatten)]
    pub global: GlobalFlags,

    #[command(subcommand)]
    pub command: Commands,
}

/// Global flags, available on every subcommand.
#[derive(Debug, Args, Clone)]
#[command(next_help_heading = "Global options")]
pub struct GlobalFlags {
    /// Profile (Zendesk instance) to target
    #[arg(
        short = 'p',
        long,
        global = true,
        env = "ZENDESK_PROFILE",
        value_name = "NAME"
    )]
    pub profile: Option<String>,

    /// Override the subdomain for this call (the `acme` in acme.zendesk.com)
    #[arg(long, global = true, value_name = "SUB")]
    pub subdomain: Option<String>,

    /// Output format (default: table on a terminal, json when piped)
    #[arg(short = 'o', long, global = true, value_enum, value_name = "FORMAT")]
    pub output: Option<OutputArg>,

    /// Keep only these fields (dot paths, comma-separated), e.g. id,subject,assignee.name
    #[arg(long, global = true, value_name = "A,B,C", value_delimiter = ',', action = ArgAction::Append)]
    pub fields: Vec<String>,

    /// Drop these fields (dot paths, comma-separated)
    #[arg(long, global = true, value_name = "A,B", value_delimiter = ',', action = ArgAction::Append)]
    pub exclude: Vec<String>,

    /// Single-line JSON
    #[arg(long, global = true)]
    pub compact: bool,

    /// Post-process with an embedded jq-compatible filter
    #[arg(long, global = true, value_name = "EXPR")]
    pub jq: Option<String>,

    /// Auto-paginate to completion
    #[arg(long, global = true, alias = "paginate")]
    pub all: bool,

    /// Stop after N records
    #[arg(long, global = true, value_name = "N", value_parser = clap::value_parser!(u64).range(1..))]
    pub limit: Option<u64>,

    /// Records per page (1-100)
    #[arg(long, global = true, value_name = "N", value_parser = clap::value_parser!(u32).range(1..=100))]
    pub page_size: Option<u32>,

    /// Request sideloads, e.g. users,groups,comment_count
    #[arg(long, global = true, value_name = "A,B", value_delimiter = ',', action = ArgAction::Append)]
    pub sideload: Vec<String>,

    /// Print the request that would be sent and consume no quota
    #[arg(long, global = true)]
    pub dry_run: bool,

    /// Skip destructive-action confirmation
    #[arg(short = 'y', long, global = true)]
    pub yes: bool,

    /// Explicit Idempotency-Key for writes (auto-generated by default)
    #[arg(long, global = true, value_name = "KEY")]
    pub idempotency_key: Option<String>,

    /// What to do when a rate-limit budget is exhausted
    #[arg(long, global = true, value_enum, value_name = "STRATEGY")]
    pub rate_limit_strategy: Option<StrategyArg>,

    /// In-flight request ceiling
    #[arg(long, global = true, value_name = "N", value_parser = clap::value_parser!(u32).range(1..))]
    pub max_concurrency: Option<u32>,

    /// Per-request timeout in seconds
    #[arg(long, global = true, value_name = "SECS", value_parser = clap::value_parser!(u64).range(1..))]
    pub timeout: Option<u64>,

    /// Maximum attempts per request (overrides [retry].max_attempts)
    #[arg(long, global = true, value_name = "N")]
    pub retries: Option<u32>,

    /// Suppress non-error output on stderr (warnings, progress)
    #[arg(short = 'q', long, global = true)]
    pub quiet: bool,

    /// Increase verbosity (-v info, -vv debug, -vvv trace with redacted request/response logs)
    #[arg(short = 'v', long = "verbose", global = true, action = ArgAction::Count)]
    pub verbose: u8,

    /// Disable colour (NO_COLOR is also honoured)
    #[arg(long, global = true)]
    pub no_color: bool,

    /// Append a structured NDJSON record of every API call to this file
    #[arg(long, global = true, value_name = "PATH")]
    pub audit_log: Option<PathBuf>,

    /// Alternative config file (also ZENDESK_CONFIG)
    #[arg(long, global = true, value_name = "PATH")]
    pub config: Option<PathBuf>,

    /// Where credentials are kept
    #[arg(long, global = true, value_enum, value_name = "STORE")]
    pub credential_store: Option<StoreArg>,

    /// Write pagination progress to this file and resume from it
    #[arg(long, global = true, value_name = "PATH")]
    pub checkpoint: Option<PathBuf>,

    /// Base URL override (tests and proxies)
    #[arg(
        long,
        global = true,
        hide = true,
        env = "ZENDESK_BASE_URL",
        value_name = "URL"
    )]
    pub base_url: Option<String>,
}

impl GlobalFlags {
    /// Convert into the argv-free struct `zdk-core` resolves settings from.
    #[must_use]
    pub fn to_global_args(&self, stdout_is_tty: bool) -> GlobalArgs {
        GlobalArgs {
            profile: self.profile.clone(),
            subdomain: self.subdomain.clone(),
            output: self.output.map(OutputArg::into_format),
            fields: self.fields.clone(),
            exclude: self.exclude.clone(),
            compact: self.compact,
            jq: self.jq.clone(),
            all: self.all,
            limit: self.limit,
            page_size: self.page_size,
            sideload: self.sideload.clone(),
            dry_run: self.dry_run,
            yes: self.yes,
            idempotency_key: self.idempotency_key.clone(),
            rate_limit_strategy: self.rate_limit_strategy.map(StrategyArg::into_strategy),
            max_concurrency: self.max_concurrency,
            timeout: self.timeout,
            retries: self.retries,
            quiet: self.quiet,
            verbosity: self.verbose,
            no_color: self.no_color,
            audit_log: self.audit_log.clone(),
            config: self.config.clone(),
            credential_store: self.credential_store.map(StoreArg::into_selector),
            checkpoint: self.checkpoint.clone(),
            base_url: self.base_url.clone(),
            stdout_is_tty,
        }
    }
}

/// `-o` values (mirrors `zdk_core::output::OutputFormat` so clap can list them).
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum OutputArg {
    Table,
    Json,
    Ndjson,
    Csv,
    Tsv,
    Yaml,
    Raw,
}

impl OutputArg {
    #[must_use]
    pub const fn into_format(self) -> OutputFormat {
        match self {
            Self::Table => OutputFormat::Table,
            Self::Json => OutputFormat::Json,
            Self::Ndjson => OutputFormat::Ndjson,
            Self::Csv => OutputFormat::Csv,
            Self::Tsv => OutputFormat::Tsv,
            Self::Yaml => OutputFormat::Yaml,
            Self::Raw => OutputFormat::Raw,
        }
    }
}

/// `--rate-limit-strategy` values.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum StrategyArg {
    /// Sleep until the budget refills (default)
    Wait,
    /// Exit 7 as soon as a budget is exhausted
    Fail,
    /// Skip the local governor; rely on 429 handling
    Burst,
}

impl StrategyArg {
    #[must_use]
    pub const fn into_strategy(self) -> RateLimitStrategy {
        match self {
            Self::Wait => RateLimitStrategy::Wait,
            Self::Fail => RateLimitStrategy::Fail,
            Self::Burst => RateLimitStrategy::Burst,
        }
    }
}

/// `--credential-store` values.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
pub enum StoreArg {
    /// OS keyring when available, else the encrypted file
    Auto,
    Keyring,
    File,
    /// Read-only: ZENDESK_ACCESS_TOKEN / ZENDESK_EMAIL + ZENDESK_API_TOKEN
    Env,
    /// In-memory only (tests)
    None,
}

impl StoreArg {
    #[must_use]
    pub const fn into_selector(self) -> StoreSelector {
        match self {
            Self::Auto => StoreSelector::Auto,
            Self::Keyring => StoreSelector::Keyring,
            Self::File => StoreSelector::File,
            Self::Env => StoreSelector::Env,
            Self::None => StoreSelector::None,
        }
    }
}

/// Top-level commands.
#[derive(Debug, Subcommand)]
pub enum Commands {
    /// Manage the config file and profiles
    Config(crate::cmd::config::ConfigArgs),

    /// Generate shell completions (bash, zsh, fish, powershell, elvish)
    Completions {
        /// Shell to generate for
        #[arg(value_enum)]
        shell: clap_complete::Shell,
    },

    /// Write man pages (zdk.1 and one per subcommand) into a directory
    Man {
        /// Output directory (created if missing)
        #[arg(long, value_name = "DIR")]
        to: PathBuf,
    },

    /// Print version information
    Version,

    /// Log in and manage OAuth / API-token credentials
    Auth(crate::cmd::auth::AuthArgs),

    /// Tickets: list, get, show, create, update, reply, assign, solve, delete
    Tickets(crate::cmd::tickets::TicketsArgs),

    /// Ticket comments: list, count, make private, redact
    Comments(crate::cmd::comments::CommentsArgs),

    /// Users and end users
    Users(crate::cmd::users::UsersArgs),

    /// Organizations
    Orgs(crate::cmd::orgs::OrgsArgs),

    /// Search tickets, users and organizations
    Search(crate::cmd::search::SearchArgs),

    /// Raw API escape hatch: any method and path, plus the operation registry
    Api(crate::cmd::api::ApiArgs),

    /// Check auth, connectivity, rate limits and local configuration
    Doctor(crate::cmd::doctor::DoctorArgs),
}

impl Commands {
    /// Commands that must still run when the config file is unparsable (so it can be fixed).
    #[must_use]
    pub fn tolerates_broken_config(&self) -> bool {
        use crate::cmd::config::ConfigCommand;
        match self {
            Self::Config(args) => matches!(
                args.command,
                ConfigCommand::Init(_)
                    | ConfigCommand::Edit
                    | ConfigCommand::Validate
                    | ConfigCommand::Path
            ),
            Self::Completions { .. } | Self::Man { .. } | Self::Version => true,
            Self::Auth(_)
            | Self::Tickets(_)
            | Self::Comments(_)
            | Self::Users(_)
            | Self::Orgs(_)
            | Self::Search(_)
            | Self::Api(_)
            | Self::Doctor(_) => false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    #[test]
    fn command_tree_is_well_formed() {
        Cli::command().debug_assert();
    }

    #[test]
    fn every_global_flag_from_the_prd_is_defined() {
        let mut cmd = Cli::command();
        cmd.build();
        let longs: Vec<String> = cmd
            .get_arguments()
            .filter_map(|a| a.get_long().map(str::to_string))
            .collect();
        for flag in [
            "profile",
            "subdomain",
            "output",
            "fields",
            "exclude",
            "compact",
            "jq",
            "all",
            "limit",
            "page-size",
            "sideload",
            "dry-run",
            "yes",
            "idempotency-key",
            "rate-limit-strategy",
            "max-concurrency",
            "timeout",
            "retries",
            "quiet",
            "verbose",
            "no-color",
            "audit-log",
            "config",
            "credential-store",
            "checkpoint",
            "base-url",
        ] {
            assert!(longs.contains(&flag.to_string()), "missing --{flag}");
        }
        // Deliberately undefined so they fail with exit 2 until implemented.
        for flag in ["all-profiles", "resolve-names", "no-cache"] {
            assert!(
                !longs.contains(&flag.to_string()),
                "--{flag} should not exist yet"
            );
        }
    }

    #[test]
    fn global_flags_convert_to_global_args() {
        let cli = Cli::try_parse_from([
            "zdk",
            "-p",
            "prod",
            "-o",
            "ndjson",
            "--fields",
            "id,subject",
            "--fields",
            "status",
            "--paginate",
            "--limit",
            "5",
            "--rate-limit-strategy",
            "fail",
            "--credential-store",
            "none",
            "-vv",
            "version",
        ])
        .unwrap();
        let g = cli.global.to_global_args(false);
        assert_eq!(g.profile.as_deref(), Some("prod"));
        assert_eq!(g.output, Some(OutputFormat::Ndjson));
        assert_eq!(g.fields, vec!["id", "subject", "status"]);
        assert!(g.all);
        assert_eq!(g.limit, Some(5));
        assert_eq!(g.rate_limit_strategy, Some(RateLimitStrategy::Fail));
        assert_eq!(g.credential_store, Some(StoreSelector::None));
        assert_eq!(g.verbosity, 2);
        assert!(!g.stdout_is_tty);
    }

    #[test]
    fn page_size_is_bounded() {
        assert!(Cli::try_parse_from(["zdk", "--page-size", "0", "version"]).is_err());
        assert!(Cli::try_parse_from(["zdk", "--page-size", "101", "version"]).is_err());
        assert!(Cli::try_parse_from(["zdk", "--page-size", "100", "version"]).is_ok());
    }
}
